In [1]:
import pandas as pd
import numpy as np

In [55]:
#loading a dataset -- Anime CSV

anime = pd.read_csv(r"C:\Users\KondasaniBalaji\ai_training\Week1\Day5\anime.csv")

anime.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [90]:
# a new column for feature extraction

def extract_episodes(title):
    data=""
    i=0
    while i< len(title):
        if title[i]=="(":
            i+=1
            while i<len(title) and title[i]!=")":
                if title[i].isnumeric():
                    data+=title[i]
                i+=1
            break
        i+=1
    return int(data)

In [91]:
anime["episode_count"]=anime["Title"].apply(extract_episodes)
anime

,Rank,Title,Score,Release,start,end,duration_months,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,15,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,5,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,11,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,3,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,Apr 2011 - Mar 2012,2011-04-01,2012-03-01,11,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,Jan 2021 - Jan 2021,2021-01-01,2021-01-01,0,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,35,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,Apr 2022 - Jun 2022,2022-04-01,2022-06-01,2,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,Oct 2012 - Mar 2013,2012-10-01,2013-03-01,5,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,Mar 2023 - May 2023,2023-03-01,2023-05-01,2,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,110,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,1,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,Apr 2021 - Jun 2021,2021-04-01,2021-06-01,2,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,2,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,47,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,Sep 2016 - Sep 2016,2016-09-01,2016-09-01,0,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,Oct 2017 - Mar 2018,2017-10-01,2018-03-01,5,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,Oct 2008 - Mar 2009,2008-10-01,2009-03-01,5,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,Apr 2008 - Sep 2008,2008-04-01,2008-09-01,5,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,Jul 2013 - Jul 2013,2013-07-01,2013-07-01,0,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,Sep 2020 - Sep 2020,2020-09-01,2020-09-01,0,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,Aug 2017 - Aug 2017,2017-08-01,2017-08-01,0,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,Jul 2018 - Oct 2018,2018-07-01,2018-10-01,3,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,Apr 2004 - Sep 2005,2004-04-01,2005-09-01,17,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,Aug 2016 - Aug 2016,2016-08-01,2016-08-01,0,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,0,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,0,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,Jan 2023 - Jun 2023,2023-01-01,2023-06-01,5,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,1,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,Jan 2018 - Mar 2018,2018-01-01,2018-03-01,2,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,Apr 2020 - Oct 2021,2020-04-01,2021-10-01,18,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,Jan 2019 - Apr 2019,2019-01-01,2019-04-01,3,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,Dec 2020 - Mar 2021,2020-12-01,2021-03-01,3,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,Dec 2021 - Feb 2022,2021-12-01,2022-02-01,2,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,Jan 2017 - Jan 2017,2017-01-01,2017-01-01,0,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,Apr 2023 - Jun 2023,2023-04-01,2023-06-01,2,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,Oct 2016 - Dec 2016,2016-10-01,2016-12-01,2,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,Jul 2001 - Jul 2001,2001-07-01,2001-07-01,0,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,Jul 2013 - Dec 2013,2013-07-01,2013-12-01,5,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,Jan 2022 - Apr 2022,2022-01-01,2022-04-01,3,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,17,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,Apr 1998 - Apr 1999,1998-04-01,1999-04-01,12,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,Apr 2022 - Oct 2022,2022-04-01,2022-10-01,6,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,Jul 2019 - Dec 2019,2019-07-01,2019-12-01,5,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,Oct 2014 - Dec 2014,2014-10-01,2014-12-01,2,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,2,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,Feb 1999 - Sep 1999,1999-02-01,1999-09-01,7,4

In [100]:
def extract_timestamp(title):
    i=0
    data=""
    while i < len(title):
        if title[i]==")":
            data+=title[i+1:i+20]
            break
        i+=1
    return int(data)

In [101]:
anime["Release"] = anime["Title"].apply(extract_timestamp)
anime.head()

ValueError: invalid literal for int() with base 10: 'Apr 2009 - Jul 2010'

In [102]:
# convert timestamp to months
anime[['start', 'end']] = anime['Release'].str.split(' - ', expand=True)

anime['start'] = pd.to_datetime(anime['start'], format='%b %Y')
anime['end'] = pd.to_datetime(anime['end'], format='%b %Y')

anime['duration_months'] = (
    (anime['end'].dt.year - anime['start'].dt.year) * 12
    + (anime['end'].dt.month - anime['start'].dt.month)
)

anime[['duration_months']].head()

   duration_months
0               15
1                5
2                2
3               11
4                3

In [103]:
# retrieve anime with highest score
anime.head()
anime[anime["Score"]==anime["Score"].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [104]:
# top d anime with highest score
anime.sort_values(by="Score").head(9)

,Rank,Title,Score,Release,start,end,duration_months,episode_count
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,2,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,Feb 1999 - Sep 1999,1999-02-01,1999-09-01,7,4
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,2,12
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,Oct 2014 - Dec 2014,2014-10-01,2014-12-01,2,10
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,Jul 2019 - Dec 2019,2019-07-01,2019-12-01,5,24
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,Apr 1998 - Apr 1999,1998-04-01,1999-04-01,12,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,Apr 2022 - Oct 2022,2022-04-01,2022-10-01,6,26
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,17,75
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,Jul 2013 - Dec 2013,2013-07-01,2013-12-01,5,26

In [105]:
# retrieve anime with highest episode count
anime.sort_values(by="episode_count",ascending=False)[["Title","episode_count"]].head(1)

                                                Title  episode_count
15  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...            201

In [106]:
# largest running anime

anime.sort_values(by="duration_months",ascending=False)[["Title","duration_months"]].head(1)

                                                Title  duration_months
11  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...              110

In [107]:
# top e episode count
anime.sort_values(by="episode_count",ascending=False).head(4)

,Rank,Title,Score,Release,start,end,duration_months,episode_count
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,47,201
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,35,148
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,110,110
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,17,75